services:
  postgres:
    image: postgres:17
    container_name: langgraph-postgres-2
    ports:
      - "5443:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:v1.19.0
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage

  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot
    ports:
      - "7860:7860"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - qdrant

volumes:
  pgdata:
  qdrant-data:
